name: Promover Dev para Produção

on:
  workflow_dispatch:
    inputs:
      dev_branch:
        description: 'Nome do branch de preview (ex: dev-abc123)'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: luisbianconi/aulao-pipeline
          path: aulao-pipeline

      - name: Criar branch de produção correspondente
        run: |
          cd aulao-pipeline
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          git fetch origin ${{ github.event.inputs.dev_branch }}
          PROD_BRANCH="${{ github.event.inputs.dev_branch/dev/prd }}"
          git checkout -b "$PROD_BRANCH" origin/${{ github.event.inputs.dev_branch }}
          git push origin "$PROD_BRANCH"
